[package]
name = "shadertoy-rs"
version = "0.1.0"
authors = ["Federico Menozzi <federicogmenozzi@gmail.com>"]

[dependencies]
gfx = "0.14"
gfx_window_glutin = "0.14"
glutin = "0.7"
clap = { version = "2.23.2", features = ["yaml"] }
image = "0.13"

[[example]]
name = "seascape"
path = "examples/seascape/main.rs"

[[example]]
name = "elemental-ring"
path = "examples/elemental-ring/main.rs"
